# CI to build things from OSLib.
#

name: BuildFromOSLib

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Set up the virtualenv
        run: |
          sudo apt-get install virtualenv
          virtualenv venv
          venv/bin/pip install -r requirements.txt

      - name: Run the build of everything
        run: |
          source venv/bin/activate
          ./build-all-apis.sh

      - uses: actions/upload-artifact@v2
        with:
          name: CPython
          path: artifacts/CPython/*
